{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pubg-map.serviceAccountName" . }}
  labels:
    {{- include "pubg-map.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
